<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="AdminPlataformas.aspx.cs" Inherits="PRESENTACION.AdminPlataformas" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            margin-bottom: 76px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="col-md-10">
        <div class="container">
            <h3>Agregar Nueva Plataforma</h3>
            <hr />
            <div class="row">
                <div class="form-inline">
                    <asp:Label ID="Label1" runat="server" Text="Ingrese el nombre de la nueva plataforma:"></asp:Label>
                    &nbsp;
                    <asp:TextBox ID="TxtNombre" runat="server"></asp:TextBox>
                   
                    &nbsp;&nbsp;
                   
                    <asp:Button ID="btnAgregar" runat="server" Text="Agregar" CssClass="btn btn-danger" OnClick="btnAgregar_Click" />
                </div>
            </div>
        </div>
        <br />
        <h3>Plataformas</h3>

        <div class="col-lg-2">

            <asp:GridView ID="grdPlataformas" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="grdPlataformas_RowDeleting" OnRowEditing="grdPlataformas_RowEditing" OnRowUpdating="grdPlataformas_RowUpdating" AllowPaging="True" OnRowCancelingEdit="grdPlataformas_RowCancelingEdit" PageSize="7" Font-Size="Medium" Font-Strikeout="False" Width="454px" CssClass="auto-style1">
                <Columns>
                    <asp:TemplateField HeaderText="Código">
                        <EditItemTemplate>
                            <asp:Label ID="lbl_eit_codigoPlataforma" runat="server" Text='<%# Bind("Cod_Plataforma_p") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_eit_codigoPlataforma" runat="server" Text='<%# Bind("Cod_Plataforma_p") %>'></asp:Label>
                        </ItemTemplate>
                        <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_nombrePlataforma" runat="server" Text='<%# Bind("Nombre_Plataforma_p") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_NombrePataforma" runat="server" Text='<%# Bind("Nombre_Plataforma_p") %>'></asp:Label>
                        </ItemTemplate>
                        <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
                <HeaderStyle BackColor="#CC0000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="#330099" HorizontalAlign="Center" />
                <RowStyle BackColor="White" ForeColor="#330099" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                <SortedAscendingCellStyle BackColor="#FEFCEB" />
                <SortedAscendingHeaderStyle BackColor="#AF0101" />
                <SortedDescendingCellStyle BackColor="#F6F0C0" />
                <SortedDescendingHeaderStyle BackColor="#7E0000" />
            </asp:GridView>
        </div>
         </div>
</asp:Content>
