<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="AdminProductos.aspx.cs" Inherits="PRESENTACION.AdminProductos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            height: 36px;
        }
    </style>
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <div class ="col-lg-10">
    <div class="row">
            <div class="col-lg-10">
                 <h3> Productos</h3>
                <hr />
                    </div>
                 </div>
            
     

        <div class="row">
 
 
<div class="col-lg-2">
    <asp:Button class="btn btn-danger" ID="Button10" runat="server" Text="Agregar Producto" />
    </div>



           </div>
          <div class="row">
 
 
<div class="col-lg-2">

    </div>
           </div>

           <div class="row">
    <div class="col-lg-2">
 

 <div class="input-group">
      <div class="input-group-prepend">
    <input type="text" class="form-control" placeholder="Producto"/>
    <div class="input-group-btn">
      <button class="btn btn-danger" type="submit" >Buscar</button>
    </div>
  </div>
     </div>
            </div>

                              &nbsp
                <div class="dropdown">
                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Plataformas
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Nintendo Switch</a>
                        <a class="dropdown-item" href="#">Nintendo 3ds</a>
                        <a class="dropdown-item" href="#">Playstation 3</a>
                        <a class="dropdown-item" href="#">Playstation 4</a>
                        <a class="dropdown-item" href="#">PS Vita</a>
                        <a class="dropdown-item" href="#">Xbox 360</a>
                        <a class="dropdown-item" href="#">Xbox One</a>
                        <a class="dropdown-item" href="#">Pc</a>
                    </div>
                </div>
                               &nbsp
                <div class="dropdown">
                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categorias
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Video Juego</a>
                        <a class="dropdown-item" href="#">Accesorio</a>
                    </div>
                </div>
                                              &nbsp
                <div class="dropdown">
                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Marcas
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Nintendo</a>
                        <a class="dropdown-item" href="#">Sony</a>
                        <a class="dropdown-item" href="#">Logitech</a>
                        <a class="dropdown-item" href="#">Microsoft</a>
                    </div>
                </div>
               </div>
                            
                                <div class="col-lg-2">
                                <asp:GridView ID="grdProductos" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Width="1173px" OnRowCancelingEdit="grdProductos_RowCancelingEdit" OnRowDataBound="grdProductos_RowDataBound" OnRowDeleting="grdProductos_RowDeleting" OnRowEditing="grdProductos_RowEditing" OnRowUpdating="grdProductos_RowUpdating" OnPageIndexChanging="grdProductos_PageIndexChanging">
                                    <Columns>
                                        <asp:TemplateField HeaderText="Código">
                                            <EditItemTemplate>
                                                <asp:Label ID="lbl_eit_codigo" runat="server" Text='<%# Bind("Codigo") %>'></asp:Label>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_it_Codigo" runat="server" Text='<%# Bind("Codigo") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Nombre">
                                            <EditItemTemplate>
                                                <asp:TextBox ID="txt_eit_nombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:TextBox>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_it_Nombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Descripción">
                                            <EditItemTemplate>
                                                <asp:TextBox ID="txt_eit_descripcion" runat="server" Text='<%# Bind("Descripcion") %>'></asp:TextBox>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_it_Descripcion" runat="server" Text='<%# Bind("Descripcion") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Marca">
                                            <EditItemTemplate>
                                                <asp:DropDownList ID="ddl_eit_marca" runat="server">
                                                </asp:DropDownList>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_it_Marca" runat="server" Text='<%# Bind("NombreMarca") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Categoría">
                                            <EditItemTemplate>
                                                <asp:DropDownList ID="ddl_eit_categoria" runat="server">
                                                </asp:DropDownList>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_it_Categoria" runat="server" Text='<%# Bind("NombreCategoria") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Género">
                                            <EditItemTemplate>
                                                <asp:DropDownList ID="ddl_eit_genero" runat="server">
                                                </asp:DropDownList>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_it_Genero" runat="server" Text='<%# Bind("NombreGenero") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Fecha de Publicación">
                                            <EditItemTemplate>
                                                <asp:TextBox ID="lbl_eit_FPublicacion" runat="server" Text='<%# Bind("FPublicacion") %>' TextMode="DateTime"></asp:TextBox>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_it_FPublicacion" runat="server" Text='<%# Bind("FPublicacion") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Precio Unitario">
                                            <EditItemTemplate>
                                                <asp:TextBox ID="txt_eit_PrecioUnitario" runat="server"></asp:TextBox>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_it_PrecioUnitario" runat="server" Text='<%# Bind("PrecioUnitario") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Stock">
                                            <EditItemTemplate>
                                                <asp:TextBox ID="txt_eit_stock" runat="server" ></asp:TextBox>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="lbl_it_Stock" runat="server" Text='<%# Bind("Stock") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                    </Columns>
                <EditRowStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
                <HeaderStyle BackColor="#CC0000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="#330099" HorizontalAlign="Center" />
                <RowStyle BackColor="White" ForeColor="#330099" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                <SortedAscendingCellStyle BackColor="#FEFCEB" />
                <SortedAscendingHeaderStyle BackColor="#AF0101" />
                <SortedDescendingCellStyle BackColor="#F6F0C0" />
                <SortedDescendingHeaderStyle BackColor="#7E0000" />
                                    </asp:GridView>
                                    </div>
                                


                  
                </div>
 
</asp:Content>