<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="AdminMarca.aspx.cs" Inherits="PRESENTACION.Formulario_web13" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <div class ="col-lg-10">
    <div class="row">
            <div class="col-lg-10">

                    <h3> Marcas</h3>
                <hr />
                    </div>
                 </div>
            
     

        <div class="row">
 
 
<div class="col-lg-2">
    <asp:Button class="btn btn-danger" ID="Button10" runat="server" Text="Agregar Marca" />
    </div>
           </div>
          <div class="row">
 
 
<div class="col-lg-2">

    </div>
           </div>

           <div class="row">
    <div class="col-lg-10">
 
        <asp:Label ID="lblBuscarMarca" runat="server" Text="Ingrese nombre de marca a buscar: "></asp:Label>

            &nbsp;<asp:TextBox ID="txtNombreMarca" runat="server"></asp:TextBox>
&nbsp;
        <asp:Button class="btn btn-danger" ID="btnAceptar" runat="server" Text="Aceptar" OnClick="btnAceptar_Click" />

            </div>
               </div>

         <div class="col-lg-2">
             <asp:GridView ID="grdMarcas" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnPageIndexChanging="grdMarcas_PageIndexChanging" OnRowCancelingEdit="grdMarcas_RowCancelingEdit" OnRowDeleting="grdMarcas_RowDeleting" OnRowEditing="grdMarcas_RowEditing" OnRowUpdating="grdMarcas_RowUpdating" Height="308px" Width="917px">
                 <Columns>
                     <asp:TemplateField HeaderText="Código">
                         <EditItemTemplate>
                             <asp:Label ID="lbl_eit_Codigo" runat="server" Text='<%# Bind("Cod_Marca_M") %>'></asp:Label>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_Codigo" runat="server" Text='<%# Bind("Cod_Marca_M") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Nombre">
                         <EditItemTemplate>
                             <asp:TextBox ID="txt_eit_nombre" runat="server" Text='<%# Bind("Nombre_Marca_M") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_nombre" runat="server" Text='<%# Bind("Nombre_Marca_M") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Contacto">
                         <EditItemTemplate>
                             <asp:TextBox ID="txt_eit_contacto" runat="server" Text='<%# Bind("Nombre_Contacto_M") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_contacto" runat="server" Text='<%# Bind("Nombre_Contacto_M") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Dirección">
                         <EditItemTemplate>
                             <asp:TextBox ID="txt_eit_direccion" runat="server" Text='<%# Bind("Direccion_Marca_M") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_direccion" runat="server" Text='<%# Bind("Direccion_Marca_M") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Ciudad">
                         <EditItemTemplate>
                             <asp:TextBox ID="txt_eit_ciudad" runat="server" Text='<%# Bind("Ciudad_Marca_M") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_Ciudad" runat="server" Text='<%# Bind("Ciudad_Marca_M") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Teléfono">
                         <EditItemTemplate>
                             <asp:TextBox ID="txt_eit_Telefono" runat="server" Text='<%# Bind("Telefono_Marca_M") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_Telefono" runat="server" Text='<%# Bind("Telefono_Marca_M") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Email">
                         <EditItemTemplate>
                             <asp:TextBox ID="txt_eit_email" runat="server" Text='<%# Bind("Email_Marca_M") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_Email" runat="server" Text='<%# Bind("Email_Marca_M") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                 </Columns>
                                 <EditRowStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
                <HeaderStyle BackColor="#CC0000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="#330099" HorizontalAlign="Center" />
                <RowStyle BackColor="White" ForeColor="#330099" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                <SortedAscendingCellStyle BackColor="#FEFCEB" />
                <SortedAscendingHeaderStyle BackColor="#AF0101" />
                <SortedDescendingCellStyle BackColor="#F6F0C0" />
                <SortedDescendingHeaderStyle BackColor="#7E0000" />
             </asp:GridView>
    </div>
                </div>
 
 

 
 
</asp:Content>
