<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="AdminPlataformas.aspx.cs" Inherits="PRESENTACION.AdminPlataformas" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            margin-bottom: 76px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="col-md-10">
        <div class="container">
            <h3>Agregar Nueva Plataforma</h3>
            <hr />
            <div class="row">
                <div class="form-inline">
                    <asp:Label ID="Label1" runat="server" Text="INGRESE EL NOMBRE DE LA NUEVA PLATAFORMA:"></asp:Label>
                    &nbsp;
                    <asp:TextBox ID="TxtNombre" runat="server" CssClass="rounded"></asp:TextBox>                   
                    &nbsp;                   
                    <asp:Button ID="btnAgregar" runat="server" Text="AGREGAR" CssClass="btn btn-danger" OnClick="btnAgregar_Click" />
                </div>
            </div>
        </div>
        <hr />    
        <h3>Plataformas</h3>

        <div class="col-lg-2">

            <asp:GridView ID="grdPlataformas" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="grdPlataformas_RowDeleting" OnRowEditing="grdPlataformas_RowEditing" OnRowUpdating="grdPlataformas_RowUpdating" OnRowCancelingEdit="grdPlataformas_RowCancelingEdit" Font-Size="Medium" Font-Strikeout="False" Width="454px" Height="177px" AllowPaging="True" OnPageIndexChanging="grdPlataformas_PageIndexChanging" CellPadding="4" ForeColor="#333333" GridLines="None" PageSize="5">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:TemplateField HeaderText="Código">
                        <EditItemTemplate>
                            <asp:Label ID="lbl_eit_codigoPlataforma" runat="server" Text='<%# Bind("Cod_Plataforma_p") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_eit_codigoPlataforma" runat="server" Text='<%# Bind("Cod_Plataforma_p") %>'></asp:Label>
                        </ItemTemplate>
                        <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_nombrePlataforma" runat="server" Text='<%# Bind("Nombre_Plataforma_p") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_nombrePlataforma" runat="server" Text='<%# Bind("Nombre_Plataforma_p") %>'></asp:Label>
                        </ItemTemplate>
                        <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle HorizontalAlign="Center" VerticalAlign="Middle" BackColor="#999999" />
                <FooterStyle BackColor="#dc3545" ForeColor="White" Font-Bold="True" />
                <HeaderStyle BackColor="#dc3545" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#dc3545" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
        </div>
         </div>
</asp:Content>
