<%@ Page Title="" Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="PRESENTACION.Carrito" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="Content/Carrito.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    
    <div class="container-fluid" style="background-color:crimson">
        <br />
        <br />
        <h2 style="color:white;text-align:center">CARRITO</h2>
        <br />
        <div class="main row">
            <div class="col-lg-2" style="background-color:crimson"></div>
            <div class="col-lg-8" style="background-color:white">
                <div class="container">   
                <asp:GridView ID="grdCarrito" CssClass="Grid" runat="server" ShowHeader="False" AutoGenerateColumns="False"  AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="grdCarrito_RowDeleting" OnRowCancelingEdit="grdCarrito_RowCancelingEdit" OnRowEditing="grdCarrito_RowEditing" OnRowUpdating="grdCarrito_RowUpdating">
                    <Columns>
                        <asp:TemplateField HeaderText="PRODUCTO">
                            <EditItemTemplate>
                                <asp:Image ID="imgProducto" runat="server" ImageUrl='<%# Bind("ImgUrl") %>' /> 
                            </EditItemTemplate>
                            <ItemTemplate>
                                    <asp:Image ID="imgBtnProducto" runat="server" ImageUrl='<%# Bind("ImgUrl") %>' />
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="NOMBRE">
                            <EditItemTemplate>
                                <h5><asp:Label ID="lblNombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:Label></h5>                
                            </EditItemTemplate>
                            <ItemTemplate>
                                <h5><asp:Label ID="lblNombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:Label></h5>                  
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="PLATAFORMA">
                            <EditItemTemplate>
                                <h7><asp:Label ID="lblPlataforma" runat="server" Text='<%# Bind("Plataforma") %>'></asp:Label></h7>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <h7><asp:Label ID="lblPlataforma" runat="server" Text='<%# Bind("Plataforma") %>'></asp:Label></h7>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="CANTIDAD">
                            <EditItemTemplate>
                                Cantidad: 
                                <asp:TextBox ID="txtCantidad" runat="server" type="number" min="1" max="10" Text='<%# Bind("Cantidad") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <h7>Cantidad: <asp:Label ID="lblCantidad" runat="server" Text='<%# Bind("Cantidad") %>'></asp:Label></h7>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="PRECIO">
                            <EditItemTemplate>
                                <h7>$<asp:Label ID="lblPrecio" runat="server" Text='<%# Bind("PrecioUnitario") %>'></asp:Label></h7>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <h7>$<asp:Label ID="lblPrecio" runat="server" Text='<%# Bind("PrecioUnitario") %>'></asp:Label></h7>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#FFFFFF" ForeColor="#FFFFFF" />
                    <RowStyle BackColor="White" ForeColor="#330099" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                    <SortedAscendingCellStyle BackColor="#FEFCEB" />
                    <SortedAscendingHeaderStyle BackColor="#AF0101" />
                    <SortedDescendingCellStyle BackColor="#F6F0C0" />
                    <SortedDescendingHeaderStyle BackColor="#7E0000" />
                </asp:GridView>
                </div>
                <h3 style="color:crimson;text-align:right">Total: $<%=this.Session["PrecioTotal"] %></h3>
                 <br />
                 <br />
            </div>
            <div class="col-lg-2" style="background-color:crimson"></div>
        </div>
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8" style="text-align:center;background-color:white">
                <asp:Button ID="btnComprar" runat="server" class="btn btn-danger" Text="FINALIZAR COMPRA"  OnClick="btnComprar_Click" />
                <br />
                <br />
            </div>
            <div class="col-lg-2"></div>
        </div>
        
        <div class="row" style="background-color:crimson">
        <br />
        <br />
        <br />
        </div>

    </div>

</asp:Content>
