<%@ Page Title="" Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="PRESENTACION.Carrito" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="container-fluid" style="background-color:crimson">
        <br />
        <br />
        <br />
        <div class="main row">
            <div class="col-lg-3" style="background-color:crimson"></div>
            <div class="col-lg-7" style="background-color:crimson">
                <asp:GridView ID="grdCarrito" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#DC143C" BorderStyle="None" BorderWidth="2px" CellPadding="4" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="grdCarrito_RowDeleting" OnRowCancelingEdit="grdCarrito_RowCancelingEdit" OnRowEditing="grdCarrito_RowEditing" OnRowUpdating="grdCarrito_RowUpdating">
                    <Columns>
                        <asp:TemplateField HeaderText="PRODUCTO">
                            <EditItemTemplate>
                                <asp:Image ID="imgProducto" runat="server" Height="100px" ImageUrl='<%# Bind("ImgUrl") %>' Width="100px" />
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Image ID="imgBtnProducto" runat="server" Height="100px" ImageUrl='<%# Bind("ImgUrl") %>' Width="100px" />
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="NOMBRE">
                            <EditItemTemplate>
                                <asp:Label ID="lblNombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblNombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="PLATAFORMA">
                            <EditItemTemplate>
                                <asp:Label ID="lblPlataforma" runat="server" Text='<%# Bind("Plataforma") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblPlataforma" runat="server" Text='<%# Bind("Plataforma") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="CANTIDAD">
                            <EditItemTemplate>
                                <asp:DropDownList ID="ddlCantidad" runat="server" SelectedValue='<%# Bind("Cantidad") %>'>
                                    <asp:ListItem>1</asp:ListItem>
                                    <asp:ListItem>2</asp:ListItem>
                                    <asp:ListItem>3</asp:ListItem>
                                    <asp:ListItem>4</asp:ListItem>
                                    <asp:ListItem>5</asp:ListItem>
                                    <asp:ListItem>6</asp:ListItem>
                                    <asp:ListItem>7</asp:ListItem>
                                    <asp:ListItem>8</asp:ListItem>
                                    <asp:ListItem>9</asp:ListItem>
                                    <asp:ListItem>10</asp:ListItem>
                                </asp:DropDownList>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblCantidad" runat="server" Text='<%# Bind("Cantidad") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="PRECIO UNITARIO">
                            <EditItemTemplate>
                                <asp:Label ID="lblPrecio" runat="server" Text='<%# Bind("PrecioUnitario") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                $<asp:Label ID="lblPrecio" runat="server" Text='<%# Eval("PrecioUnitario") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#FFFFFF" ForeColor="#FFFFFF" />
                    <HeaderStyle BackColor="#DC143C" Font-Bold="True" ForeColor="#FFFFFF" />
                    <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
                    <RowStyle BackColor="White" ForeColor="#330099" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                    <SortedAscendingCellStyle BackColor="#FEFCEB" />
                    <SortedAscendingHeaderStyle BackColor="#AF0101" />
                    <SortedDescendingCellStyle BackColor="#F6F0C0" />
                    <SortedDescendingHeaderStyle BackColor="#7E0000" />
                </asp:GridView>
            </div>
            <div class="col-lg-2" style="background-color:crimson"></div>
        </div>
        <br />
        <br />
        <br />
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-5" style="text-align:center;background-color:crimson">
                <asp:Button ID="btnComprar" runat="server" class="btn btn-warning" Text="FINALIZAR COMPRA"  OnClick="btnComprar_Click" />
            </div>
            <div class="col-lg-4"></div>
        </div>
        <br />
        <br />
        <br />

    </div>

</asp:Content>
